import { GUITAR_TUNINGS } from '@moonwave99/fretboard.js';
export const config = {
  el:'#fretboard',
  tuning:GUITAR_TUNINGS.default,//["E2", "A2", "D3", "G3", "B3", "E4"],
  stringCount:6,
  stringWidth:1,
  stringColor:'#00f',
  fretCount:24,
  fretWidth:1,
  fretColor:'#666',
  nutWidth:7,
  nutColor:'#666',
  middleFretColor:'#ff636c',
  middleFretWidth:3,
  scaleFrets:true,
  topPadding:15,
  bottomPadding:5,
  leftPadding:15,
  rightPadding:15,
  height:150,
  width:1160,
  dotSize:25,
  dotStrokeColor:'#555',
  dotStrokeWidth:1,
  dotTextSize:10,
  dotFill: ({ inBox }) => (inBox ? 'cyan' : 'lightgray'),
  disabledOpacity:0.7,
  showFretNumbers:true,
  fretNumbersHeight:40,
  fretNumbersMargin:20,
  fretNumbersColor:'#33333399',
  font:'Verdana',
  crop:false,
  fretLeftPadding:0,
  barresColor:'#666'  
};

